---
- name: Creating the number of kvm defined by the user in env_variables file
  hosts: 127.0.0.1
  connection: local
  become: true
  vars_files:
    - "./env_variables"

  tasks:
     
     - name: Run sh script which creates n number of vm in localhost
       command:  sh install_vm.sh  {{no_of_vm}} {{prefix_of_vm}}  vm_hardware_config.cfg   
       args:
        chdir: ../Auto-Deploy-KVM/
       
